### ISSUE TITLE
When will the fix for django 3.2 be released?

### ISSUE THREAD

**Issue by my-umd** [jazzband/django-revproxy#144] opened 2022-03-12 22:34 UTC
Not sure if there is a better channel to ask this question.  I see 0.11.0, which has fix for django 3.2, has not been released.  Any plan when to release it?  Thanks.

**Comment by brianmay** [comment] 2022-04-01 05:30
I think we need to fix the items in https://github.com/jazzband/django-revproxy/issues/129 first. At least as many as possible.

Unfortunately, I simply do not have time to look at this.

**Comment by smit-mehta25** [comment] 2022-05-17 08:33
@seocam @brianmay Any updates on this one?

**Comment by JeroenJADS** [comment] 2022-07-05 08:01
This has been fixed in #148!

**Comment by chiatt** [comment] 2022-09-02 18:51
Hi @JeroenJADS, this fix works great, but to @my-umd's question, it's not yet released on PyPi. This is a problem because the latest django-revproxy (with the fix) can't be used as a dependency in a requirements.txt file for a project published on PyPi. Locally the github url to the master branch can be used, but PyPi will reject that for security reasons.

**Comment by matjazsu** [comment] 2022-10-06 15:21
Hi @JeroenJADS,

> Hi @JeroenJADS, this fix works great, but to @my-umd's question, it's not yet released on PyPi. This is a problem because the latest django-revproxy (with the fix) can't be used as a dependency in a requirements.txt file for a project published on PyPi. Locally the github url to the master branch can be used, but PyPi will reject that for security reasons.

any news regarding ^^?

**Comment by medihack** [comment] 2022-10-27 13:48
I can confirm that the current master branch works correctly with Django 4.1. So a new release would be nice.

**Comment by andruten** [comment] 2022-11-25 08:20
I think a new release could be released as some tasks from #129 have been resolved.

**Comment by andruten** [comment] 2023-01-12 12:47
@brianmay Could you please publish a new release? :) Thanks!

**Comment by brianmay** [comment] 2023-02-23 04:32
Unfortunately I have no time to even look at this package. Is the `CHANGELOG.rst` up to date for the next release? If not it would help if somebody provided a PR to update this.

**Comment by andruten** [comment] 2023-02-23 08:56
Done!  https://github.com/jazzband/django-revproxy/pull/162

**Comment by brianmay** [comment] 2023-02-25 00:41
My 1st attempt to release failed. https://github.com/jazzband/django-revproxy/actions/runs/4267415470/jobs/7428996053

Probably something trivial wrong, no idea what.

**Comment by andruten** [comment] 2023-02-25 07:01
Thank you for your time. I'll take a look. I think this is happening because of the version file.

**Comment by andruten** [comment] 2023-02-25 08:18
https://github.com/jazzband/django-revproxy/pull/163 may fix the issue :).

**Comment by andruten** [comment] 2023-02-25 22:35
@brianmay 0.11.0 tag may be removed and recreated again using HEAD commit of master branch. Thanks in advance.

**Comment by andruten** [comment] 2023-02-25 22:39
I see it is still giving 500 error during upload process... :(

**Comment by brianmay** [comment] 2023-02-25 22:41
I did that, but it didn't work out. Oh, crap that was my fault. Somehow I thought my git repo was up-to-date when it wasn't which led to a sequence of errors on my end.

Yes, still not working. No idea why.

**Comment by andruten** [comment] 2023-02-25 22:43
Thank you! I'm looking into this...

**Comment by andruten** [comment] 2023-02-25 22:56
@brianmay Is the `JAZZBAND_RELEASE_KEY` secret filled?

**Comment by brianmay** [comment] 2023-02-25 22:58
Not 100% sure, but it doesn't look like it to me.

**Comment by andruten** [comment] 2023-02-25 22:59
Once secret it's set you can't see it anymore. You may see it blank but it can be there.

**Comment by brianmay** [comment] 2023-02-25 23:01
![output](https://user-images.githubusercontent.com/112729/221383510-cb33f95e-925d-4f4f-87b5-c49a9c7bb244.png)

Looks like not set to me. Similar if I click variables.

**Comment by andruten** [comment] 2023-02-25 23:06
Ok, thank you! Who could add that secrets? 🤔 

I've joined the Jazzband organization and I've assigned to myself as a [team member](https://jazzband.co/projects/django-revproxy). 

I think I can publish releases and manage issues now but my PRs still need at least one approval.

**Comment by brianmay** [comment] 2023-02-25 23:08
Lets see then if you can publish this release :-)

**Comment by andruten** [comment] 2023-02-25 23:10
I'll remove 0.11.0 and 0.11.1 tags and I'll recreate again.

**Comment by brianmay** [comment] 2023-02-25 23:21
Sounds good. Don't forget to update the `CHANGELOG.rst` and `revproxy/__init__.py` files also :-)

**Comment by andruten** [comment] 2023-02-25 23:21
Oops! On it!

**Comment by andruten** [comment] 2023-02-25 23:22
Done!

**Comment by brianmay** [comment] 2023-02-25 23:24
Approved. I think you should be able to merge it. Once the CI is done.

**Comment by andruten** [comment] 2023-02-25 23:26
Yes! :D I've merged it and I've created a new release... Hope it works...

**Comment by brianmay** [comment] 2023-02-25 23:28
Doesn't look good :-(

**Comment by andruten** [comment] 2023-02-25 23:28
It didn't 🥲. I think this is related to that secret.

**Comment by andruten** [comment] 2023-02-25 23:37
I've published an issue in jazzband help repository. I'll let you know...!

**Comment by medihack** [comment] 2023-03-12 21:13
Can this be closed?

**Comment by andruten** [comment] 2023-03-12 21:44
Not yet as 0.11.0 is not available in PyPi. There is [an issue](https://github.com/jazzband/help/issues/330) in the jazzband/help repository.

**Comment by acangiani** [comment] 2023-05-24 20:18
@andruten or @brianmay there is a comment on how to fix the release of 0.11.0 on the [Jazzband issue](https://github.com/jazzband/help/issues/330#issuecomment-1554008335), can you try it out?

**Comment by brianmay** [comment] 2023-05-24 21:56
No, that is not a work around we can implement. It is just asking the user to download the package from github instead of PyPi.

**Comment by acangiani** [comment] 2023-05-25 19:41
Ok, sorry for creating noise, very much appreciate it.

**Comment by andruten** [comment] 2023-10-07 00:24
Finally, version 0.11.0 has been released 🥲 

https://pypi.org/project/django-revproxy/#description

I'm closing this.

**Closed by andruten** 2023-10-07 00:24 UTC
